from django.contrib import admin
from .models import *

admin.site.register(db_admin)
admin.site.register(front_desk)
admin.site.register(data_entry)
admin.site.register(physician)
admin.site.register(department)
admin.site.register(affiliated_with)
admin.site.register(trained_in)
admin.site.register(procedures)
admin.site.register(room)
admin.site.register(patient)
admin.site.register(undergoes)
admin.site.register(prescribes)
admin.site.register(stay)
admin.site.register(block)
admin.site.register(on_call)
admin.site.register(medication)
admin.site.register(appointment)
admin.site.register(nurse)